### ISSUE TITLE
Add `Expect` based end to end tests

### ISSUE THREAD

**Issue by ultimatecoder** [ultimatecoder/geeksforgeek#2]
## Description

Add [expect](https://core.tcl.tk/expect/index) based end to end tests for existing solution.

## Task

- [ ] Write end to end test for `maximum_in_struct_array.py` utility.
- [ ] Add description of the tool at the `REDME.md` file
  - [ ] Mention the tool in the dependency
  - [ ] Add command at Makefile to run the tests
